// packages/vue/src/components/Button.vue
<template>
  <psypres-button
    :variant="variant"
    :size="size"
    :disabled="disabled"
    v-bind="$attrs"
    @click="onClick"
  >
    <slot></slot>
  </psypres-button>
</template>

<script>
import '@psypres/shared-ui';

export default {
  name: 'PsypresButton',
  inheritAttrs: false,
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: (value) => ['primary', 'secondary', 'outline'].includes(value)
    },
    size: {
      type: String,
      default: 'medium',
      validator: (value) => ['small', 'medium', 'large'].includes(value)
    },
    disabled: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    onClick(event) {
      this.$emit('click', event.detail.originalEvent);
    }
  }
};
</script>

// packages/react/src/Button.jsx
import React, { useRef, useEffect, forwardRef } from 'react';
import '@psypres/shared-ui';

const Button = forwardRef(({
  children,
  variant = 'primary',
  size = 'medium',
  disabled = false,
  onClick,
  ...props
}, ref) => {
  const buttonRef = useRef(null);
  
  // Combine refs
  useEffect(() => {
    if (!ref) return;
    
    if (typeof ref === 'function') {
      ref(buttonRef.current);
    } else {
      ref.current = buttonRef.current;
    }
  }, [ref]);
  
  // Setup event listeners
  useEffect(() => {
    const buttonElement = buttonRef.current;
    if (!buttonElement) return;
    
    const handleClick = (e) => {
      if (onClick) onClick(e.detail.originalEvent);
    };
    
    buttonElement.addEventListener('click', handleClick);
    
    return () => {
      buttonElement.removeEventListener('click', handleClick);
    };
  }, [onClick]);
  
  return (
    <psypres-button
      ref={buttonRef}
      variant={variant}
      size={size}
      disabled={disabled ? true : undefined}
      {...props}
    >
      {children}
    </psypres-button>
  );
});

Button.displayName = 'Button';

export default Button;
