// packages/vue/src/components/ThemeProvider.vue
<template>
  <psypres-theme-provider
    :theme="theme"
    v-bind="$attrs"
  >
    <slot></slot>
  </psypres-theme-provider>
</template>

<script>
import '@psypres/shared-ui';

export default {
  name: 'PsypresThemeProvider',
  inheritAttrs: false,
  props: {
    theme: {
      type: String,
      default: null
    }
  }
};
</script>

// packages/react/src/ThemeProvider.jsx
import React, { forwardRef } from 'react';
import '@psypres/shared-ui';

const ThemeProvider = forwardRef(({
  children,
  theme,
  ...props
}, ref) => {
  return (
    <psypres-theme-provider
      ref={ref}
      theme={theme}
      {...props}
    >
      {children}
    </psypres-theme-provider>
  );
});

ThemeProvider.displayName = 'ThemeProvider';

export default ThemeProvider;
