// packages/react/src/ThemeToggle.jsx
import React, { forwardRef } from 'react';
import '@psypres/shared-ui';

const ThemeToggle = forwardRef(({
  size = 'medium',
  ...props
}, ref) => {
  return (
    <psypres-theme-toggle
      ref={ref}
      size={size}
      {...props}
    />
  );
});

ThemeToggle.displayName = 'ThemeToggle';

export default ThemeToggle;

// packages/vue/src/components/ThemeToggle.vue
<template>
  <psypres-theme-toggle
    :size="size"
    v-bind="$attrs"
  />
</template>

<script>
import '@psypres/shared-ui';

export default {
  name: 'PsypresThemeToggle',
  inheritAttrs: false,
  props: {
    size: {
      type: String,
      default: 'medium',
      validator: (value) => ['small', 'medium', 'large'].includes(value)
    }
  }
};
</script>
